cache:
  paths:
    - node_modules/
    - dist/
  key: "$CI_PIPELINE_ID"

stages:
  - build
  - test
  - lint
  - deploy

build:
  image: node:alpine
  stage: build
  script:
    - npm install
    - npm run build

test:
  image: node:alpine
  needs:
    - build
  stage: test
  script:
    - npm install --no-save mocha-junit-reporter
    - npm run test -- --reporter mocha-junit-reporter
  artifacts:
    reports:
      junit:
      - test-results.xml

lint:
  image: node:alpine
  needs:
    - build
  stage: lint
  script:
    - npm install
    - npm run lint -- --format junit --output-file test-lint.xml
  artifacts:
    reports:
      junit:
      - test-lint.xml

deploy:
  image: node:alpine
  stage: deploy
  only:
    - tags
  needs:
    - lint
    - test
    - build
  script:
    - |
      sed -i "s|\"name\": \"durak\"|\"name\": \"@${CI_PROJECT_NAMESPACE}/durak\"|" package.json
    - |
      echo "@${CI_PROJECT_NAMESPACE}:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
      echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm publish --scope "@${CI_PROJECT_NAMESPACE}"
