cache:
  paths:
    - node_modules/
    - dist/

stages:
  - build
  - test
  - lint

build:
  image: node:alpine
  stage: build
  script:
    - npm install
    - npm run build

test:
  image: node:alpine
  needs:
    - build
  stage: test
  script:
    - npm install --no-save mocha-junit-reporter
    - npm run test -- --reporter mocha-junit-reporter
  artifacts:
    reports:
      junit:
      - test-results.xml

lint:
  image: node:alpine
  needs:
    - build
  stage: lint
  script:
    - npm install
    - npm run lint -- --format junit --output-file test-lint.xml
  artifacts:
    reports:
      junit:
      - test-lint.xml